### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by EvertonMelo** [republicprotocol/republic-whitepaper#1]
add license of use. 

examples:

CCv4
MIT

**Comment by loongy** [comment]
We are not sure about making the whitepaper MIT licensed. The official reference implementation is licensed under MIT, but the whitepaper and official specification may not be. Will keep this issue open, as deciding on a license is a good idea. Until then, the default copyright applies.

**Comment by loongy** [comment]
License has been added. Closing this issue.
